import path from "node:path";
import fs from "node:fs";
import prompts from "prompts";
import { logger } from "../utils/logger";
import { readConfig, DEFAULT_CONFIG, type CodeUiConfig } from "../utils/config";
import { getRegistryItem, listRegistryItems } from "../registry";
import { installDependencies } from "../utils/pm";

function generateTypesDts(installedComponents: string[], config: CodeUiConfig): string {
  const prefix = config.prefix || "cui-";
  let content = `/* Auto-generated by @code-ui/cli. Do not edit manually. */\n\n`;
  content += `export interface CuiCommonElementProps {\n  id?: string;\n  class?: string;\n  className?: string;\n  style?: string | Record<string, any>;\n  slot?: string;\n  key?: string | number;\n  children?: any;\n}\n\n`;

  if (installedComponents.includes("button")) {
    content += `export interface CuiButtonElementProps extends CuiCommonElementProps {\n  loading?: boolean;\n  disabled?: boolean;\n  variant?: "primary" | "secondary" | "outline" | "ghost" | "danger";\n  size?: "sm" | "md" | "lg";\n  loadingAuto?: boolean;\n  autoResetDuration?: number;\n  openType?: string;\n  formType?: string;\n  onTap?: (event?: any) => void;\n  onClick?: (event?: any) => void;\n  onGetPhoneNumber?: (event?: any) => void;\n  onChooseAvatar?: (event?: any) => void;\n}\n\n`;
  }

  if (installedComponents.includes("drawer")) {
    content += `export interface CuiDrawerElementProps extends CuiCommonElementProps {\n  open?: boolean;\n  placement?: "bottom" | "top" | "left" | "right";\n  closeOnBackdropClick?: boolean;\n  dismissible?: boolean;\n  threshold?: number;\n  duration?: number;\n  onClose?: (event?: any) => void;\n  onOpenChange?: (event?: any) => void;\n}\n\n`;
  }

  content += `declare global {\n  namespace JSX {\n    interface IntrinsicElements {\n`;
  if (installedComponents.includes("button")) {
    content += `      "${prefix}button": CuiButtonElementProps;\n`;
  }
  if (installedComponents.includes("drawer")) {
    content += `      "${prefix}drawer": CuiDrawerElementProps;\n`;
  }
  content += `    }\n  }\n}\n`;

  return content;
}

export async function addCommand(
  components: string[],
  options: { yes?: boolean; overwrite?: boolean; cwd?: string; noDeps?: boolean } = {}
) {
  const cwd = options.cwd || process.cwd();
  let config = readConfig(cwd);

  if (!config) {
    logger.warn("code-ui.json not found. Using default configuration.");
    config = DEFAULT_CONFIG;
  }

  let selectedComponents = components;

  if (!selectedComponents || selectedComponents.length === 0) {
    const available = listRegistryItems();
    const { picked } = await prompts({
      type: "multiselect",
      name: "picked",
      message: "Select components to add to your project:",
      choices: available.map((item) => ({
        title: `${item.name} - ${item.description}`,
        value: item.name,
      })),
      min: 1,
    });
    selectedComponents = picked || [];
  }

  if (selectedComponents.length === 0) {
    logger.info("No components selected. Aborted.");
    return;
  }

  const allDependencies = new Set<string>();
  const installedComponents: string[] = [];

  // Check already installed components in directory
  const componentBaseDir = path.resolve(cwd, config.componentDir);
  if (fs.existsSync(componentBaseDir)) {
    const existingDirs = fs.readdirSync(componentBaseDir, { withFileTypes: true });
    for (const d of existingDirs) {
      if (d.isDirectory() && getRegistryItem(d.name)) {
        installedComponents.push(d.name);
      }
    }
  }

  for (const name of selectedComponents) {
    const item = getRegistryItem(name);
    if (!item) {
      logger.error(`Component "${name}" not found in registry. Run "code-ui list" to see available components.`);
      continue;
    }

    const componentTargetDir = path.resolve(cwd, config.componentDir, name);
    if (!fs.existsSync(componentTargetDir)) {
      fs.mkdirSync(componentTargetDir, { recursive: true });
    }

    for (const file of item.files) {
      let fileName = file.name;
      // If user selected scss style and file is wxss, rename extension
      if (config.style === "scss" && fileName.endsWith(".wxss")) {
        fileName = fileName.replace(".wxss", ".scss");
      }

      const filePath = path.join(componentTargetDir, fileName);
      if (fs.existsSync(filePath) && !options.overwrite) {
        if (!options.yes) {
          const { confirmOverwrite } = await prompts({
            type: "confirm",
            name: "confirmOverwrite",
            message: `${path.relative(cwd, filePath)} already exists. Overwrite?`,
            initial: false,
          });
          if (!confirmOverwrite) {
            continue;
          }
        }
      }

      fs.writeFileSync(filePath, file.content, "utf-8");
      logger.success(`Created ${path.relative(cwd, filePath)}`);
    }

    for (const dep of item.dependencies) {
      allDependencies.add(dep);
    }
    if (!installedComponents.includes(name)) {
      installedComponents.push(name);
    }
  }

  // Generate automated types.d.ts in components directory if TypeScript is enabled
  if (config.typescript) {
    const typesFilePath = path.resolve(cwd, config.componentDir, "types.d.ts");
    const typesContent = generateTypesDts(installedComponents, config);
    fs.writeFileSync(typesFilePath, typesContent, "utf-8");
    logger.success(`Generated JSX types at ${logger.highlight(path.relative(cwd, typesFilePath))}`);
  }

  if (!options.noDeps && allDependencies.size > 0) {
    logger.info(`Installing dependencies: ${Array.from(allDependencies).join(", ")}...`);
    try {
      installDependencies(Array.from(allDependencies), { cwd });
      logger.success("Dependencies installed successfully.");
    } catch (err: any) {
      logger.warn(`Could not automatically install dependencies. Please run: pnpm add ${Array.from(allDependencies).join(" ")}`);
    }
  }

  if (selectedComponents.length > 0) {
    logger.success(
      `Successfully added ${selectedComponents.map((c) => logger.highlight(c)).join(", ")} to ${logger.highlight(config.componentDir)}!`
    );
  }
}
