import fs from "node:fs/promises";
import path from "node:path";
import type { CodeUIPluginOptions } from "../types";

function toPascalCase(str: string): string {
  return str
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

/**
 * Dynamically generates a TypeScript declaration file (types/code-ui.d.ts)
 * declaring only the selected/active components in JSX.IntrinsicElements.
 */
export async function generateTypes(
  appPath: string,
  targetComponents: string[],
  options: CodeUIPluginOptions = {},
): Promise<void> {
  if (options.injectTypes === false) {
    return;
  }

  if (targetComponents.length === 0) {
    return;
  }

  // Determine target directory: prefer app/types, fallback to app/src
  let targetDir = path.join(appPath, "types");
  try {
    await fs.access(targetDir);
  } catch {
    targetDir = path.join(appPath, "types");
    await fs.mkdir(targetDir, { recursive: true });
  }

  const dtsFilePath = path.join(targetDir, "code-ui.d.ts");

  const elements = targetComponents.map((name) => {
    const pascal = toPascalCase(name);
    return {
      tag: `cui-${name.toLowerCase()}`,
      propType: `Cui${pascal}ElementProps`,
    };
  });

  const imports = elements.map((e) => e.propType).join(",\n  ");
  const intrinsicProps = elements
    .map((e) => `"${e.tag}": ${e.propType};`)
    .join("\n      ");

  const content = `/* Auto-generated by @code-ui/plugin-taro - do not edit directly */
import type {
  ${imports},
} from "@code-ui/components";

declare global {
  namespace JSX {
    interface IntrinsicElements {
      ${intrinsicProps}
    }
  }
}

export {};
`;

  await fs.writeFile(dtsFilePath, content, "utf-8");
  console.log(
    `[code-ui] 📝 Injected JSX types for [${targetComponents.join(", ")}] → ${path.relative(appPath, dtsFilePath)}`,
  );
}
