/* Auto-generated by @code-ui/plugin-taro - do not edit directly */
import type {
  CuiDrawerElementProps,
  CuiButtonElementProps,
} from "@code-ui/components";

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "cui-drawer": CuiDrawerElementProps;
      "cui-button": CuiButtonElementProps;
    }
  }
}

export {};
